# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Борис\програмирование\свои проекты\myday\mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(842, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(836, 630))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 630))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ChooseLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.ChooseLabel.setFont(font)
        self.ChooseLabel.setObjectName("ChooseLabel")
        self.horizontalLayout_5.addWidget(self.ChooseLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.ListOfPosts = QtWidgets.QListWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListOfPosts.sizePolicy().hasHeightForWidth())
        self.ListOfPosts.setSizePolicy(sizePolicy)
        self.ListOfPosts.setObjectName("ListOfPosts")
        self.verticalLayout.addWidget(self.ListOfPosts)
        self.listOfTagsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.listOfTagsButton.setObjectName("listOfTagsButton")
        self.verticalLayout.addWidget(self.listOfTagsButton)
        self.NewPostButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.NewPostButton.setObjectName("NewPostButton")
        self.verticalLayout.addWidget(self.NewPostButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 10, 591, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.Date = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Date.setObjectName("Date")
        self.horizontalLayout_4.addWidget(self.Date)
        self.pixmapLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pixmapLabel.setText("")
        self.pixmapLabel.setObjectName("pixmapLabel")
        self.horizontalLayout_4.addWidget(self.pixmapLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setInputMask("")
        self.lineEdit.setMaxLength(250)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RedactorButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.RedactorButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RedactorButton.sizePolicy().hasHeightForWidth())
        self.RedactorButton.setSizePolicy(sizePolicy)
        self.RedactorButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.RedactorButton.setObjectName("RedactorButton")
        self.horizontalLayout_3.addWidget(self.RedactorButton)
        self.DeleteButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.DeleteButton.setEnabled(False)
        self.DeleteButton.setObjectName("DeleteButton")
        self.horizontalLayout_3.addWidget(self.DeleteButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.Author = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Author.sizePolicy().hasHeightForWidth())
        self.Author.setSizePolicy(sizePolicy)
        self.Author.setMidLineWidth(0)
        self.Author.setObjectName("Author")
        self.horizontalLayout_3.addWidget(self.Author)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 700, 311, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мой дневник"))
        self.ChooseLabel.setText(_translate("MainWindow", "Выберите запись:"))
        self.listOfTagsButton.setText(_translate("MainWindow", "Список тегов"))
        self.NewPostButton.setText(_translate("MainWindow", "Новая запись"))
        self.Date.setText(_translate("MainWindow", "12.10.1905, 17:26"))
        self.label.setText(_translate("MainWindow", "Теги:"))
        self.RedactorButton.setText(_translate("MainWindow", "  Редактировать запись  "))
        self.DeleteButton.setText(_translate("MainWindow", "  Удалить запись  "))
        self.Author.setText(_translate("MainWindow", "Автор: Истигечев Борис. Картинки взяты с Интернета."))

